name: windows

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setting up the environment
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        echo "Setting up environment variables..."
        # Set environment variables on Windows
        echo "NGROK_AUTH_TOKEN=$NGROK_AUTH_TOKEN" >> $GITHUB_ENV

    - name: Run install_ngrok.ps1
      run: .\install_ngrok.ps1 -NGROK_AUTH_TOKEN $env:NGROK_AUTH_TOKEN

    - name: Display ngrok URL
      run: |
        # Wait for ngrok to start (adjust sleep time as needed)
        Start-Sleep -Seconds 10

        # Display ngrok URL
        $ngrok_url = (Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels | Select-Object -ExpandProperty tunnels | Select-Object -First 1 -ExpandProperty public_url)
        echo "Ngrok URL: $ngrok_url"

    - name: Wait for 24 hours
      run: Start-Sleep -Seconds 86400  # 24 hours in seconds

    - name: Ending Session
      run: echo "Windows End MF"
