name: windows

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setting up the environment
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        echo "Setting up environment variables..."
        # Set environment variables on Windows
        echo "NGROK_AUTH_TOKEN=$NGROK_AUTH_TOKEN" >> $GITHUB_ENV

    - name: Enable TS
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

    - name: Enable Remote Desktop Firewall Rule
      run: |
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set Terminal Server User Authentication
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Create Password
      run: |
        $securePassword = ConvertTo-SecureString -String "Rabiu2004@" -AsPlainText -Force

    - name: Create Tunnel
      run: .\ngrok.exe tcp 3389

    - name: Wait for 24 hours
      run: Start-Sleep -Seconds 86400  # 24 hours in seconds

    - name: Ending Session
      run: echo "Windows End MF"
